---
title: "TMAO analysis"
author: "zero"
date: "6/12/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 一些函数
```{r}
to_factor <- function(df){#from Tmisc::unfactor
  id <- sapply(df, is.character)
    df[id] <- lapply(df[id], as.factor)
    df
}
cha_to_fac <- function(df){
  id <- sapply(df,is.character)
  df[id] <- lapply(df[id],as.factor)
  df
}
to_impute <- function(df){#from Tmisc::unfactor
  id <- sapply(df, is.numeric)
    df[id] <- lapply(df[id], FUN=impute)
    df[id] <- lapply(df[id], as.numeric)
    df
}
get_num <- function(df){
  id <- sapply(df,is.numeric)
  df[id]
}
get_unum <- function(df){#from Tmisc::unfactor
  id <- sapply(df, is.numeric)
    df[-id]
}
get_fac <- function(df){
  id <- sapply(df,is.factor)
  df[id]
}
get_p <- function(x,fac,na.omit=TRUE,paired=FALSE,digits = 3){
  if(na.omit)
    x <- x[!is.na(x)]
  if(shapiro.test(x)$p.value >0.05){
    test<- t.test(x~fac,paired = FALSE)
  }
  else{
    test <- wilcox.test(x~fac,paired = FALSE)
  }
  return(signif(test$p.value,digits = digits))
}
get_stat_num <- function(x,na.omit=TRUE,digits=3){
  library(stringr)
  library(dplyr)
  if(na.omit)
    x <- x[!is.na(x)]
  if(shapiro.test(x)$p.value >0.05){
    m <- signif(mean(x),digits = digits)
    s <- signif(sd(x),digits = digits)
    stat <- str_c(m,"±",s)
  }
  else{
    m <- signif(median(x),digits = digits)
    IQR_1 <- signif(quantile(x)[2],digits = digits)
    IQR_3 <- signif(quantile(x)[4],digits = digits)
    stat <- str_c(m,"(",IQR_1,"-",IQR_3,")")
  }
  return(stat)
}

get_stat_fac <- function(x,fac=fac){
  a <- table(x) %>%
    prop.table()%>%
    t() %>%
    t()*100
  b <- xtabs(~ x+fac) %>%
    prop.table(.,margin = 2) %>%
    as.data.frame.matrix() *100
  c <- xtabs(~ x +fac)%>%
    chisq.test()
  c <- c$p.value
  
  b$Total <- a
  b$p_value <- NA
  b$p_value[1] <- c
  b <- select(b,Total,everything())
}

summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the "mean" column    
    datac <- rename(datac, c("mean" = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}
eGFR_fun <- function(sex,scr,age) {
  if (sex == "男"){
    X=min(scr/(88.41*0.9),1)^-0.411
    Y=max(scr/(88.41*0.9),1)^-1.029
    Z=0.993^age
    result <- 141*X*Y*Z 
  }
  else{
    X=min(scr/(88.41*0.7),1)^-0.329
    Y=max(scr/(88.41*0.7),1)^-1.029
    Z=0.993^age
    result <- 141*X*Y*Z*1.018
  }
    return(result)
}
```



## library packages
```{r}
library(Hmisc)
library(plotly)
library(tidyverse)
library(rio)
library(readxl)
library(Tmisc)
library(stringr)
```

### 读取数据 TMAO_1_4_5
```{r}
TMAO_1_4_5 <- read_excel("~/Desktop/TMAO_ai/#_02_dplyr_TMAO/TMAO_zhangshaowu_chinese.xlsx")
id_name_tmao <- read_excel("~/Desktop/TMAO_ai/#_02_dplyr_TMAO/id_name_tmao.xlsx")
TMAO_1_4_5 <- dplyr::left_join(TMAO_1_4_5,id_name_tmao,by = c("ID号","姓名"))#combine the table 
TMAO_1_4_5$ECG <- factor(TMAO_1_4_5$ECG)
scr_z <- TMAO_1_4_5$肌酐
sex_z <- TMAO_1_4_5$性别
age_z <- TMAO_1_4_5$年龄
eGFR_Z <- c()
for(i in 1:length(sex_z)){
  eGFR_Z <- c(eGFR_Z,eGFR_fun(sex = sex_z[i],scr = scr_z[i],age = age_z[i]))
}
TMAO_1_4_5$eGFR <- eGFR_Z
TMAO_1_4_5 %>%
  remove_empty_cols() %>% remove_empty_rows() %>% Tmisc::convert_to_NA() %>%#remove empty and convert strings to NA
  mutate(血糖 = str_replace(血糖,"mmol/L","")) %>%
  mutate(TMA = as.numeric(TMA)) %>%
  mutate(血糖 = as.numeric(血糖)) %>%
  to_impute() %>%
  mutate(BMI = 体重/((身高/100)^2)) %>%
  mutate(心胸比 = if_else(心胸比=="正常","正常","异常")) %>%
  mutate(心脏超声状态 = if_else(心脏超声=="正常","正常","异常")) %>%
  #mutate(eGFR=ifelse(性别=="男",141*(min(肌酐/(88.41*0.9),1)^-0.411)*(max(肌酐/(88.41*0.9),1)^-1.029)*(0.993^年龄) ,141*(min(肌酐/(88.41*0.7),1)^-0.329)*(max(肌酐/(88.41*0.7),1)^-1.029)*(0.993^年龄)*1.018)) %>%
  mutate(CKD_stage =ifelse(eGFR <= 15,"stage_5","stage_1-4") ) %>%
    separate(血压, c("收缩压","舒张压"),sep = "/") %>%
    mutate(收缩压 = as.numeric(收缩压)) %>%
    mutate(舒张压 = as.numeric(舒张压)) %>%
    separate('胆红素(总/直接/间接)', c("总胆红素","直接胆红素","间接胆红素"),sep = "/") %>%
    mutate(总胆红素 = as.numeric(总胆红素)) %>%
    mutate(直接胆红素 = as.numeric(直接胆红素)) %>%
    mutate(间接胆红素 = as.numeric(间接胆红素)) %>%
    separate(入院日期,c("年","月","日")) %>%
      select(-c(ID号,补充的超声心动图异常和特殊时间,心电图))%>%
      to_factor() -> TMAO_1_4_5
```


## 重命名
```{r}
library(ellipse)
library(RColorBrewer)
library(psych)

TMAO_1_4_5 %>%
   select(-c(姓名,年,月,日,心脏超声,TMA,左旋肉碱)) %>%
   rename(hypertension = 高血压,
         height = 身高,
         weight = 体重,
         age = 年龄,
         diabetes = 糖尿病,
         sex = 性别,
         smoke = 吸烟,
         drink = 饮酒,
         SBP = 收缩压,
         DBP = 舒张压,
         heart_infarction = 心梗,
         Cerebrovascular_disease =脑血管病,
         heart_disease = 心脏病,
         creatinine = 肌酐,
         NYHA = 心功能分级,
         albumin = 白蛋白,
         uric_acid = 尿酸,
         total_bilirubin = 总胆红素,
         direct_bilirubin = 直接胆红素,
         indirect_bilirubin = 间接胆红素,
         Cardiothoracic_ration = 心胸比,
         blood_sugar = 血糖,
         C_reactive_protein = C反应蛋白,
         white_cell = 白细胞,
         Hemoglobin = 血色素,
         heart_ultrasound = 心脏超声状态,
         touxi = 透析#%>%  to_impute()
         )  -> TMAO_1_4_5

```

## radiant data create
```{r}
library(clipr)
TMAO_1_4_5 %>%
 filter(TMAO <= 100) %>%
  select(TMAO,Cardiothoracic_ration) %>%
  arrange(Cardiothoracic_ration) %>%
  to_impute() %>%
  clipr::write_clip()


```

## addins radiant
###
```{r}

```

# before
##三列统计表格
```{r}
ifelse(TMAO_1_4_5$TMAO <= 17.9,"low","high") %>%
  as.factor() -> TMAO_1_4_5$TMAO_group
#TMAO_1_4_5$group <- TMAO$TMAO_group
  fac <- as.factor(TMAO$TMAO_group)
  TMAO %>%
    get_num() %>%
    sapply(get_stat_num) -> a#total summary
  TMAO %>%
    filter(get("TMAO_group") == levels(fac)[1]) %>%
    get_num() %>%
    sapply(get_stat_num) -> b#summary for group_1
  TMAO %>%
    filter(get("TMAO_group") == levels(fac)[2]) %>%
    get_num() %>%
    sapply(get_stat_num) -> c#summary for group_2
  TMAO %>%
    get_num() %>%
    sapply(get_p,fac=fac) -> d#get the p value
  result_num <- rbind(a,b,c,d)
  rownames(result_num) <- c("Total",levels(fac)[1],levels(fac)[2],"p_value")
  
rio::export(t(result_num),"num_stat.xlsx",row.names =TRUE) 

  TMAO %>%
    get_fac() %>%
    select(-get("TMAO_group")) %>%
    lapply(.,get_stat_fac,fac=fac)  %>%
    do.call(rbind,.) -> result_table
p_val <- result_table$p_value
result_table <- round(result_table)
result_table$p_value <- p_val
rio::export(result_table,"fac_stat.xlsx",row.names =TRUE) 
```

##生成prism 格式的数据
```{r}
#单变量
library(radiant)
result <- explore(dataset = "TMAO_1_4_5", vars = "TMAO", byvar = "CKD_stage", fun = c("mean_rm", "sd_rm", "length"), nr = 2)
summary(result)

#多变量
result <- explore(dataset = "TMAO_1_4_5", vars = "TMAO", byvar = c("CKD_stage", "ECG"), fun = c("mean_rm", "sd_rm", "length"), nr = 6)
summary(result)
#dtab(result)
#store(result, name = "TMAO_1_4_5_rad_expl")


```

## box-plot
```{r}
library(ggplot2)
library(gridExtra)

# Make 4 simple graphics:
g1=ggplot(TMAO, aes(x=TMAO)) + geom_density(fill="slateblue") + theme_bw()
g2=ggplot(TMAO, aes(x=CKD_stage, y=TMAO, color=sex)) + geom_point(size=5) + theme(legend.position="none")+ theme_bw()
g3=ggplot(TMAO, aes(x=factor(CKD_stage), y=TMAO, fill=sex)) + geom_boxplot() + theme(legend.position="none")+ theme_bw()
tgc <- summarySE(TMAO, measurevar="TMAO", groupvars=c("CKD_stage"))
tgc
g4=ggplot(tgc, aes(x=CKD_stage, y=TMAO)) + 
    geom_bar(position=position_dodge(), stat="identity") +
    geom_errorbar(aes(ymin=TMAO-se, ymax=TMAO+se),
                  width=.2,                    # Width of the error bars
                  position=position_dodge(.9))+
  theme_bw()
 
# Show the 4 plots on the same page
grid.arrange(g1, g2, g3, g4, ncol=2, nrow =2)
# Plots
grid.arrange(g2, arrangeGrob(g3, g4, ncol=2), nrow = 2)
grid.arrange(g1, g2, g3, nrow = 3)
grid.arrange(g2, arrangeGrob(g3, g4, ncol=2), nrow = 1)
grid.arrange(g2, arrangeGrob(g3, g4, nrow=2), nrow = 1)
 
```


##相关图
```{r fig.width=22.08, fig.height=18.92, dpi = 96}
library(radiant)
TMAO %>%
  filter(CKD_stage=="stage_5") -> TMAO_rad
result <- correlation(dataset = "TMAO_rad", vars = c("age", "LVEF", "SBP", "DBP", "creatinine", "BUN", "albumin", "uric_acid", "total_bilirubin", "direct_bilirubin", "indirect_bilirubin", "CHOL", "TG", "LDL", "VLDL", "HDL", "blood_sugar", "C_reactive_protein", "white_cell", "Hemoglobin", "TMAO", "BMI"), method = "spearman")
summary(result)
plot(result, n = 1000)
```


```{r fig.width=11.58, fig.height=9.92, dpi = 96}
library(radiant)
result <- correlation(dataset = "TMAO", vars = c("age","LVEF","creatinine", "BUN", "uric_acid", "CHOL", "LDL", "HDL", "C_reactive_protein", "Hemoglobin", "TMAO"), method = "spearman")
summary(result)
plot(result, n = 1000)

#dtab(result)
#store(result, name = "TMAO_1_4_5_rad_expl")
```

### 散点图
```{r}
TMAO_1_4_5 %>%
  filter(TMAO <= 100) %>%
  filter(CKD_stage == "stage_5") %>%
  select(TMAO,age) %>%
  arrange(age) -> gg
g <- ggplot(gg,aes(x =age ,y = TMAO))
#g <- ggplot(TMAO,aes(x = eGFR,y = TMAO))
g+geom_point()+
  geom_smooth(method = "lm",color="black",se = F) +
  theme_classic()

```

##柱状图
```{r}
# Error bars represent standard error of the mean
tgc <- summarySE(TMAO, measurevar="TMAO", groupvars=c("CKD_stage","ECG"))
tgc
ggplot(tgc, aes(x=CKD_stage, y=TMAO,fill=ECG)) + 
    geom_bar(position=position_dodge(), stat="identity") +
    geom_errorbar(aes(ymin=TMAO-se, ymax=TMAO+se),
                  width=.2,                    # Width of the error bars
                  position=position_dodge(.9))+
  theme_bw()
```





##多元回归
```{r}
TMAO %>% 
  select(TMAO,creatinine,age,LVEF) %>% 
  glm(TMAO~LVEF,data=.) %>% 
  summary()
```



## t test
```{r}
t_test <- function(df,fac,num,...) {
  library(radiant)
result <- compare_means(dataset = df, var1 = fac, var2 = num)
summary(result, show = FALSE)
plot(result, plots = "scatter", custom = FALSE)
}
 t_test(df="TMAO_1_4_5",fac="heart_ultrasound",num = "TMAO")
```



```{r}
TMAO_1_4_5 %>%
  filter(CKD_stage == "stage_5") ->data
result <- compare_means(dataset = "TMAO_1_4_5", var1 = "Cardiothoracic_ration", var2 = "TMAO", test = "wilcox")
summary(result, show = FALSE)
plot(result, plots = "scatter", custom = FALSE)

```

